parentPath: '/mnt/input'
outputPath: '/mnt/output'
modelPath: '/mnt/input/matlabDependencies'
modelCatPath: '/mnt/input/matlabDependencies'
FFCPath: '/mnt/input/matlabDependencies'
numCycles: 4
row: 'BCD'
col: [2,3,4]
saveFig: 1
cytoMethod: 'RF'
MedianIntensity: 1
saveMasks: 1
applyFFC: 'ffonly'
useRFNuc: 1
segmentCytoplasm: 'segmentCytoplasm'
markerList: ['MLC2v','pS6-240','p-Src','c-Jun','CleavedCaspase3','pan14-3-3','pRb','Oct4a','B-actin','B-tubulin','pAKT-S473','pS6-235','p-mTor','NFkB','mTor','MLC2v','pS6-240','p-Src','MLC2v','pS6-240','p-Src','MLC2v','pS6-240','p-Src','MLC2v','pS6-240','p-Src','MLC2v','pS6-240','p-Src','MLC2v','pS6-240','p-Src'] 
bleachImaged: 0


%parentPath = params.inputPath;
%% outputPath = params.outputPath;
%modelPath = params.modelPath;   %.mat, static
%modelCatPath = params.modelCatPath; %.mat, static
% ip.addParamValue('NucMaskChan',[4 4],@(x)(numel(x) == 2 & all(x > 0 )));  
% ip.addParamValue('CytoMaskChan',[22 22],@(x)(numel(x) == 2 & all(x > 0 )));  
% ip.addParamValue('Row',['A' 'H'],@(x)(numel(x) == 2 & ischar(x)));  
% ip.addParamValue('Col',[1 12],@(x)(numel(x) == 2 & all(x > 0 ))); 
% ip.addParamValue('cytoMethod','RF',@(x)(ismember(x,{'RF','distanceTransform','ring'})));
% ip.addParamValue('MedianIntensity',true,@islogical);
% ip.addParamValue('saveFig',true,@islogical);
% ip.addParamValue('saveMasks',true,@islogical);
% ip.addParamValue('applyFFC','ffonly',@(x)(ismember(x,{'both','ffonly','none'})));
% ip.addParamValue('useRFNuc',true,@islogical);
% ip.addParamValue('segmentCytoplasm','segmentCytoplasm',@(x)(ismember(x,{'segmentCytoplasm','loadMask','ignoreCytoplasm'})));
