parallel: 0
NucMaskChan: [1 9]
CytoMaskChan: [10 36]
numCycles: 9
row: 'CE'
col: [4 10]
saveFig: 1
cytoMethod: 'RF'
MedianIntensity: 1
saveMasks: 1
applyFFC: 'ffonly' 
useRFNuc: 1
segmentCytoplasm: 'segmentCytoplasm'
bleachImaged: 0
markerList: [] 


